# Generated by Django 2.1.8 on 2019-04-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='duration',
        ),
        migrations.AddField(
            model_name='lesson',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='summary',
            field=models.CharField(default='', max_length=280),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
