# Generated by Django 2.1.8 on 2019-04-30 07:49

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='region',
        ),
        migrations.AddField(
            model_name='lesson',
            name='activity_type',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='age_range',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='language',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='rating',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject_matter',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='translation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='votes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='grade',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='supplies',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tags',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(default=7, max_length=280),
            preserve_default=False,
        ),
    ]
