# Generated by Django 2.1.8 on 2019-04-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190430_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
