# Generated by Django 2.1.8 on 2019-04-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190429_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='tags',
        ),
        migrations.AddField(
            model_name='lesson',
            name='tags',
            field=models.TextField(default='math, algebra'),
            preserve_default=False,
        ),
    ]
