# Generated by Django 2.1.8 on 2019-04-29 10:58

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190429_0809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='summary',
            field=models.CharField(default='', max_length=280),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
