# Generated by Django 2.1.8 on 2019-04-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190429_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subjects',
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='summary',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
